### ISSUE TITLE
ci: proposal of using release-please action

### ISSUE THREAD

**Issue by saltball** [deepmodeling/dflow#35]
# Summary

What change needs making?

> I suggest to use `release-please`(https://github.com/googleapis/release-please) action for `dflow`'s development, especially for the version number bumping, CHANGELOG generation and breaking changing warnings.
>> ci: Add a file `.github/workflow/release-please.yml`:
```yml
on:
  push:
    branches:
      - main
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: https://github.com/google-github-actions/release-please-action/tree/v3
        with:
          release-type: python
          package-name: release-please-action
```
>> docs(contribution): give clear guidance for contributors to use `conventionalcommits`(https://www.conventionalcommits.org/).

# Use Cases

When would you use this?

## for developers and maintainers
> If `dflow` uses release-please action, developers and contributors MUST write `conventionalcommits`(https://www.conventionalcommits.org/) to make `release-please` work. It will leave a clear git history and automatically generate CHANGELOG. Also, action bot will open pr for package release.
>> conventionalcommits is like this:
```
<type>[optional scope]: <description>
[optional body]
[optional footer(s)]
```
## for all users
> have clear changelog, clear git history and elegant release decisions.
- feature examples:
  - CHANGELOG of release-please itself: (https://github.com/google-github-actions/release-please-action/blob/v3/CHANGELOG.md)
    - `Bug Fixes`, `Features`, `⚠ BREAKING CHANGES` will be shown up for developers and maintainers. (with pr id and git hash)
  - A latest action bot pr (https://github.com/google-github-actions/release-please-action/pull/531)
    - developers and maintainers will be able to discuss before final release. After maintainer merged the pr, a new version with semantic versioning tag, elegant changelog and releasing package will all done automatically. Before merging, the changelog will continue update as daily developing goes. (So the pr by bot can be a developing progress board for users.)
    - Maintainers need no more manually tags.
  - And ecosystem developers, maintainers and users will use the version number to determine whether change api/scripts/tricks or not.
    - A `minor` version number changing tells me I won't change my code to use the current functions, because there are just new features or bug fixes. But a `major` version number changing tells me I must update carefully.

Hope that development of `dflow` and other or further ecosystem projects in deepmodeling community are also sufficiently automated and standardized.
